### ISSUE TITLE
[AVM Module Issue]: Can we loosen the version constraint for the azurerm provider to use its newer version? 

### ISSUE THREAD

**Issue by polikeiji** [Azure/terraform-azurerm-avm-res-devopsinfrastructure-pool#11]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

I'm trying to use this module to host pipeline agents inside my own VNET, and I'd like to manage VNET and its subnets also via Terraform.

The issue with the current version constraint for azurerm is that the old versions of azurerm including 3.71 don't support `Microsoft.DevOpsInfrastructure` as the name for delegating a subnet. It seems to be supported from 4.1.0.
https://github.com/hashicorp/terraform-provider-azurerm/pull/27259

I'm currently trying to use this module with newer version azurerm by changing the version specification from `~= 3.71` to `>= 3.71`. I'll share if it works in comments.

**Comment by jaredfholgate** [comment]
I'll take a look and see if we can support v3 and v4 for this module.

**Comment by jaredfholgate** [comment]
Released
